name             'mywebapp'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mywebapp'
long_description 'Installs/Configures mywebapp'
version          '0.1.0'
