#!/bin/bash
#
#This shell script takes care of tasks that needs to be executed before the machine is terminated
#
# chkconfig: 0123456 99 01

### BEGIN INIT INFO
# Provides: PreStopTermination
# Short-Description: to execute tasks before terminating/stopping machine
### END INIT INFO

RootEmail=BLANK
INSTANCE_ID=BLANK
INSTANCE_NAME=BLANK
APP=BLANK
SUBAPP=BLANK
Environment=BLANK
Jurisdiction=BLANK
VPC_Name=BLANK

PROGNAME=$(basename $0)

start() {
		
    touch /var/lock/subsys/${PROGNAME}
}

stop() {
    ####
	####Please put in the block of code you would like to execute before machine termination
	####
	( echo "Instance ID: ${INSTANCE_ID}"; echo "Application Name: ${APP}"; echo "Sub Application Name: `echo ${SUBAPP} | cut -c2-`"; echo "VPC: ${Environment}/${Jurisdiction}/${VPC_Name}"; echo; echo "--------"; echo ; echo)  | tee | strings | tr -d '\015' | mail -s "Terminating instance ${INSTANCE_NAME} in ${Environment}/${Jurisdiction}/${VPC_Name}: ${INSTANCE_ID}" $RootEmail
	/bin/rm -f /var/lock/subsys/${PROGNAME}
	
}
	
# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  *)
        echo $"Usage: $0 {start|stop}"
        exit 2
esac
